### ISSUE TITLE
[학습] 메뉴 기능 구현

### ISSUE THREAD

**Issue by Vactor0911** [Vactor0911/AlgoLab#22]
[**학습**] 메뉴에서 사용되는 모든 기능을 구현한다.

- [x] #35
- [x] #36
- [x] #37
- [ ] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #42

![image](https://github.com/Vactor0911/AlgoLab/assets/85281049/1f22d847-0e18-4af2-b20d-fe27319f2c1c)
[Figma 바로가기](https://www.figma.com/design/635EyivXaergN9ncYRrUrw/AlgoLab?node-id=0-1&t=bDjpCC8Y2GcqkNoJ-0)

**Comment by HeoSeonJin0504** [comment]
기능 구현 완료 (설명글은 추가 안했고 오른쪽의 시간복잡도 표 및 애니메이션 추가는 아직 안했습니다.)
