### ISSUE TITLE
[퀴즈] 메뉴 추가 논의 필요

### ISSUE THREAD

**Issue by Vactor0911** [Vactor0911/AlgoLab#61]
[퀴즈] 메뉴의 구현 및 디자인에 대하여 추가적인 논의가 필요하다.
현재 퀴즈 메뉴는 미완성된 디자인과 구현 여부가 확정되지 않은 상태이다.
따라서, 추가적인 논의를 통해 [퀴즈] 메뉴의 개발 방향성을 결정한다.

**Comment by HeoSeonJin0504** [comment]
퀴즈 화면 기능 및 퀴즈 추가 완료, 디자인은 추후 작업이 다소 필요
