### ISSUE TITLE
[학습] 메뉴 이벤트 리스너 수정 필요

### ISSUE THREAD

**Issue by Vactor0911** [Vactor0911/AlgoLab#62]
현재의 [학습] 메뉴에서는 <실습하기> 버튼을 클릭해야만 하단의 정보와 우측의 시간복잡도 데이터 등이 업데이트된다.
이것을 [학습] 메뉴에 접근했을때, 프로그램이 최초 실행되었을 때, 알고리즘 종류를 변경하였을 때 등의 상황에서 업데이트가 될 수 있도록 논리적 구조를 수정한다.

**Comment by HeoSeonJin0504** [comment]
실습하기 버튼 기능을 제외한 나머지 기능 전부 구현 완료
